name: Main Push Action

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd frontend
          npm i --force
          npm run build
          # pm2
          cd ../backend
          npm i --force
          # pm2
          cd ..
          pm2 start 0
          pm2 start 0
          pm2 save
          sudo service nginx restart